#!/bin/bash

heroku config:get BASE_URL -s  >> .env

heroku config:get FB_CLIENT_ID -s  >> .env
heroku config:get FB_CLIENT_SECRET -s  >> .env

heroku config:get SE_CLIENT_ID -s  >> .env
heroku config:get SE_CLIENT_SECRET -s  >> .env
heroku config:get SE_CLIENT_KEY -s  >> .env

heroku config:get GOOGLE_API_KEY -s >> .env
